//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estreya.BlishHUD.EventTable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estreya.BlishHUD.EventTable.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Colors to ColorPicker....
        /// </summary>
        internal static string BaseSettingsView_AddingColorsToColorPicker {
            get {
                return ResourceManager.GetString("BaseSettingsView_AddingColorsToColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ColorPicker....
        /// </summary>
        internal static string BaseSettingsView_LoadingColorPicker {
            get {
                return ResourceManager.GetString("BaseSettingsView_LoadingColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Colors....
        /// </summary>
        internal static string BaseSettingsView_LoadingColors {
            get {
                return ResourceManager.GetString("BaseSettingsView_LoadingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle in Tarir.
        /// </summary>
        internal static string event_auricBasin_battleInTarir {
            get {
                return ResourceManager.GetString("event-auricBasin-battleInTarir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending Tarir.
        /// </summary>
        internal static string event_auricBasin_defendingTarir {
            get {
                return ResourceManager.GetString("event-auricBasin-defendingTarir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial by Fire.
        /// </summary>
        internal static string event_auricBasin_trailByFire {
            get {
                return ResourceManager.GetString("event-auricBasin-trailByFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drakkar, the Ice Dragon&apos;s Champion.
        /// </summary>
        internal static string event_bjoraMarches_drakkar {
            get {
                return ResourceManager.GetString("event-bjoraMarches-drakkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storms of Winter.
        /// </summary>
        internal static string event_bjoraMarches_stormsOfWinter {
            get {
                return ResourceManager.GetString("event-bjoraMarches-stormsOfWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn.
        /// </summary>
        internal static string event_canthaDayNight_dawn {
            get {
                return ResourceManager.GetString("event-canthaDayNight-dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string event_canthaDayNight_day {
            get {
                return ResourceManager.GetString("event-canthaDayNight-day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk.
        /// </summary>
        internal static string event_canthaDayNight_dusk {
            get {
                return ResourceManager.GetString("event-canthaDayNight-dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string event_canthaDayNight_night {
            get {
                return ResourceManager.GetString("event-canthaDayNight-night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Waypoint.
        /// </summary>
        internal static string Event_CopyWaypoint {
            get {
                return ResourceManager.GetString("Event_CopyWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Blitz.
        /// </summary>
        internal static string event_crystalOasis_casinoBlitz {
            get {
                return ResourceManager.GetString("event-crystalOasis-casinoBlitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choya Pinata.
        /// </summary>
        internal static string event_crystalOasis_choyaPinata {
            get {
                return ResourceManager.GetString("event-crystalOasis-choyaPinata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn.
        /// </summary>
        internal static string event_dayNightCycle_dawn {
            get {
                return ResourceManager.GetString("event-dayNightCycle-dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string event_dayNightCycle_day {
            get {
                return ResourceManager.GetString("event-dayNightCycle-day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk.
        /// </summary>
        internal static string event_dayNightCycle_dusk {
            get {
                return ResourceManager.GetString("event-dayNightCycle-dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string event_dayNightCycle_night {
            get {
                return ResourceManager.GetString("event-dayNightCycle-night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search for Buried Treasure.
        /// </summary>
        internal static string event_desertHighland_theSearchForBuriedTreasure {
            get {
                return ResourceManager.GetString("event-desertHighland-theSearchForBuriedTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junundu Rising.
        /// </summary>
        internal static string event_desolation_jununduRising {
            get {
                return ResourceManager.GetString("event-desolation-jununduRising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maws of Torment.
        /// </summary>
        internal static string event_desolation_mawsOfTorment {
            get {
                return ResourceManager.GetString("event-desolation-mawsOfTorment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Event_Disable {
            get {
                return ResourceManager.GetString("Event_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dredgehaunt Cliffs.
        /// </summary>
        internal static string event_dragonBash_dredgehauntCliffs {
            get {
                return ResourceManager.GetString("event-dragonBash-dredgehauntCliffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lornar&apos;s Pass.
        /// </summary>
        internal static string event_dragonBash_lornarsPass {
            get {
                return ResourceManager.GetString("event-dragonBash-lornarsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowden Drifts.
        /// </summary>
        internal static string event_dragonBash_snowdenDrifts {
            get {
                return ResourceManager.GetString("event-dragonBash-snowdenDrifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wayfarer Foothills.
        /// </summary>
        internal static string event_dragonBash_wayfarerFoothills {
            get {
                return ResourceManager.GetString("event-dragonBash-wayfarerFoothills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade Maw.
        /// </summary>
        internal static string event_dragonsEnd_jadeMaw {
            get {
                return ResourceManager.GetString("event-dragonsEnd-jadeMaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparations.
        /// </summary>
        internal static string event_dragonsEnd_preparations {
            get {
                return ResourceManager.GetString("event-dragonsEnd-preparations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Battle for the Jade Sea.
        /// </summary>
        internal static string event_dragonsEnd_theBattleForTheJadeSea {
            get {
                return ResourceManager.GetString("event-dragonsEnd-theBattleForTheJadeSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancing on the Blighting Towers.
        /// </summary>
        internal static string event_dragonStand_advancingOnTheBlightingTowers {
            get {
                return ResourceManager.GetString("event-dragonStand-advancingOnTheBlightingTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Site.
        /// </summary>
        internal static string event_dryTop_crashSite {
            get {
                return ResourceManager.GetString("event-dryTop-crashSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstorm.
        /// </summary>
        internal static string event_dryTop_sandstorm {
            get {
                return ResourceManager.GetString("event-dryTop-sandstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelganger.
        /// </summary>
        internal static string event_elonRiverlands_doppelganger {
            get {
                return ResourceManager.GetString("event-elonRiverlands-doppelganger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Path to Ascension.
        /// </summary>
        internal static string event_elonRiverlands_thePathToAscension {
            get {
                return ResourceManager.GetString("event-elonRiverlands-thePathToAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonstorm.
        /// </summary>
        internal static string event_eotn_dragonstorm {
            get {
                return ResourceManager.GetString("event-eotn-dragonstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Twisted Marionette.
        /// </summary>
        internal static string event_eotn_twistedMarionette {
            get {
                return ResourceManager.GetString("event-eotn-twistedMarionette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolyak Race.
        /// </summary>
        internal static string event_festivalOfTheFourWinds_dolyakRace {
            get {
                return ResourceManager.GetString("event-festivalOfTheFourWinds-dolyakRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skimmer Race.
        /// </summary>
        internal static string event_festivalOfTheFourWinds_skimmerRace {
            get {
                return ResourceManager.GetString("event-festivalOfTheFourWinds-skimmerRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Hunt.
        /// </summary>
        internal static string event_festivalOfTheFourWinds_treasureHunt {
            get {
                return ResourceManager.GetString("event-festivalOfTheFourWinds-treasureHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Concert for the Ages.
        /// </summary>
        internal static string event_grothmar_concert {
            get {
                return ResourceManager.GetString("event-grothmar-concert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Haunting of Doomlore Shrine.
        /// </summary>
        internal static string event_grothmar_doomloreShrine {
            get {
                return ResourceManager.GetString("event-grothmar-doomloreShrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ooze Pit Trials.
        /// </summary>
        internal static string event_grothmar_oozePit {
            get {
                return ResourceManager.GetString("event-grothmar-oozePit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremony of the Sacred Flame.
        /// </summary>
        internal static string event_grothmar_sacredFlame {
            get {
                return ResourceManager.GetString("event-grothmar-sacredFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mad King says....
        /// </summary>
        internal static string event_halloween_madKingSays {
            get {
                return ResourceManager.GetString("event-halloween-madKingSays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Category.
        /// </summary>
        internal static string Event_HideCategory {
            get {
                return ResourceManager.GetString("Event_HideCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Event.
        /// </summary>
        internal static string Event_HideEvent {
            get {
                return ResourceManager.GetString("Event_HideEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palawadan, Jewel of Istan.
        /// </summary>
        internal static string event_istan_palawadan {
            get {
                return ResourceManager.GetString("event-istan-palawadan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Prey.
        /// </summary>
        internal static string event_jahai_dangerousPrey {
            get {
                return ResourceManager.GetString("event-jahai-dangerousPrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death-Branded Shatterer.
        /// </summary>
        internal static string event_jahai_deathBrandedShatterer {
            get {
                return ResourceManager.GetString("event-jahai-deathBrandedShatterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Loamhurst.
        /// </summary>
        internal static string event_lakeDoric_newLoamhurst {
            get {
                return ResourceManager.GetString("event-lakeDoric-newLoamhurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noran&apos;s Homestead.
        /// </summary>
        internal static string event_lakeDoric_noransHomestead {
            get {
                return ResourceManager.GetString("event-lakeDoric-noransHomestead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saidra&apos;s Haven.
        /// </summary>
        internal static string event_lakeDoric_saidrasHaven {
            get {
                return ResourceManager.GetString("event-lakeDoric-saidrasHaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Gendarran Fields).
        /// </summary>
        internal static string event_leyLineAnomaly_llaGF {
            get {
                return ResourceManager.GetString("event-leyLineAnomaly-llaGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Iron Marches).
        /// </summary>
        internal static string event_leyLineAnomaly_llaIM {
            get {
                return ResourceManager.GetString("event-leyLineAnomaly-llaIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Timberline Falls).
        /// </summary>
        internal static string event_leyLineAnomaly_llaTF {
            get {
                return ResourceManager.GetString("event-leyLineAnomaly-llaTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaineng Blackout.
        /// </summary>
        internal static string event_newKainengCity_kainengBlackout {
            get {
                return ResourceManager.GetString("event-newKainengCity-kainengBlackout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Waypoint found!.
        /// </summary>
        internal static string Event_NoWaypointFound {
            get {
                return ResourceManager.GetString("Event_NoWaypointFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wiki.
        /// </summary>
        internal static string Event_OpenWiki {
            get {
                return ResourceManager.GetString("Event_OpenWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balthazar&apos;s Brawl.
        /// </summary>
        internal static string event_pvpTournaments_balthazarsBrawl {
            get {
                return ResourceManager.GetString("event-pvpTournaments-balthazarsBrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenth&apos;s Game.
        /// </summary>
        internal static string event_pvpTournaments_grenthsGame {
            get {
                return ResourceManager.GetString("event-pvpTournaments-grenthsGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyssa&apos;s Legions.
        /// </summary>
        internal static string event_pvpTournaments_lyssasLegions {
            get {
                return ResourceManager.GetString("event-pvpTournaments-lyssasLegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melandru&apos;s Matchup.
        /// </summary>
        internal static string event_pvpTournaments_melandrusMatchup {
            get {
                return ResourceManager.GetString("event-pvpTournaments-melandrusMatchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetherblade Assault.
        /// </summary>
        internal static string event_seitungProvince_aetherbladeAssault {
            get {
                return ResourceManager.GetString("event-seitungProvince-aetherbladeAssault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Reset.
        /// </summary>
        internal static string event_serverReset_serverReset {
            get {
                return ResourceManager.GetString("event-serverReset-serverReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chak Gerent.
        /// </summary>
        internal static string event_tangledDepth_chakGerent {
            get {
                return ResourceManager.GetString("event-tangledDepth-chakGerent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspenwood.
        /// </summary>
        internal static string event_theEchovaldWilds_aspenwood {
            get {
                return ResourceManager.GetString("event-theEchovaldWilds-aspenwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gang War.
        /// </summary>
        internal static string event_theEchovaldWilds_gangWar {
            get {
                return ResourceManager.GetString("event-theEchovaldWilds-gangWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oil Floes.
        /// </summary>
        internal static string event_thunderheadPeaks_theOilFloes {
            get {
                return ResourceManager.GetString("event-thunderheadPeaks-theOilFloes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderhead Keep.
        /// </summary>
        internal static string event_thunderheadPeaks_thunderheadKeep {
            get {
                return ResourceManager.GetString("event-thunderheadPeaks-thunderheadKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished since.
        /// </summary>
        internal static string Event_Tooltip_FinishedSince {
            get {
                return ResourceManager.GetString("Event_Tooltip_FinishedSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string Event_Tooltip_Remaining {
            get {
                return ResourceManager.GetString("Event_Tooltip_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts at.
        /// </summary>
        internal static string Event_Tooltip_StartsAt {
            get {
                return ResourceManager.GetString("Event_Tooltip_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts in.
        /// </summary>
        internal static string Event_Tooltip_StartsIn {
            get {
                return ResourceManager.GetString("Event_Tooltip_StartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged with Fire.
        /// </summary>
        internal static string event_vabbi_forgedWithFire {
            get {
                return ResourceManager.GetString("event-vabbi-forgedWithFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpents&apos; Ire.
        /// </summary>
        internal static string event_vabbi_serpentsIre {
            get {
                return ResourceManager.GetString("event-vabbi-serpentsIre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night and the Enemy.
        /// </summary>
        internal static string event_verdantBrink_nightAndTheEnemy {
            get {
                return ResourceManager.GetString("event-verdantBrink-nightAndTheEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Bosses.
        /// </summary>
        internal static string event_verdantBrink_nightBosses {
            get {
                return ResourceManager.GetString("event-verdantBrink-nightBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securing Verdant Brink.
        /// </summary>
        internal static string event_verdantBrink_securingVerdantBrink {
            get {
                return ResourceManager.GetString("event-verdantBrink-securingVerdantBrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint copied to clipboard!.
        /// </summary>
        internal static string Event_WaypointCopied {
            get {
                return ResourceManager.GetString("Event_WaypointCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claw of Jormag.
        /// </summary>
        internal static string event_worldBosses_clawOfJormag {
            get {
                return ResourceManager.GetString("event-worldBosses-clawOfJormag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Elemental.
        /// </summary>
        internal static string event_worldBosses_fireElemental {
            get {
                return ResourceManager.GetString("event-worldBosses-fireElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquest Golem Mark II.
        /// </summary>
        internal static string event_worldBosses_golemMarkII {
            get {
                return ResourceManager.GetString("event-worldBosses-golemMarkII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Jungle Wurm.
        /// </summary>
        internal static string event_worldBosses_greatJungleWurm {
            get {
                return ResourceManager.GetString("event-worldBosses-greatJungleWurm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megadestroyer.
        /// </summary>
        internal static string event_worldBosses_megadestoryer {
            get {
                return ResourceManager.GetString("event-worldBosses-megadestoryer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modniir Ulgoth.
        /// </summary>
        internal static string event_worldBosses_modniirUlgoth {
            get {
                return ResourceManager.GetString("event-worldBosses-modniirUlgoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Behemoth.
        /// </summary>
        internal static string event_worldBosses_shadowBehemoth {
            get {
                return ResourceManager.GetString("event-worldBosses-shadowBehemoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svanir Shaman Chief.
        /// </summary>
        internal static string event_worldBosses_svanirShamanChief {
            get {
                return ResourceManager.GetString("event-worldBosses-svanirShamanChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral Taidha Covington.
        /// </summary>
        internal static string event_worldBosses_taidha {
            get {
                return ResourceManager.GetString("event-worldBosses-taidha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shatterer.
        /// </summary>
        internal static string event_worldBosses_theShatterer {
            get {
                return ResourceManager.GetString("event-worldBosses-theShatterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolved Jungle Wurm.
        /// </summary>
        internal static string event_worldBossesHardcore_evolvedJungleWurm {
            get {
                return ResourceManager.GetString("event-worldBossesHardcore-evolvedJungleWurm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karka Queen.
        /// </summary>
        internal static string event_worldBossesHardcore_karkaQueen {
            get {
                return ResourceManager.GetString("event-worldBossesHardcore-karkaQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tequatl the Sunless.
        /// </summary>
        internal static string event_worldBossesHardcore_tequatl {
            get {
                return ResourceManager.GetString("event-worldBossesHardcore-tequatl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auric Basin.
        /// </summary>
        internal static string eventCategory_auricBasin {
            get {
                return ResourceManager.GetString("eventCategory-auricBasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bjora Marches.
        /// </summary>
        internal static string eventCategory_bjoraMarches {
            get {
                return ResourceManager.GetString("eventCategory-bjoraMarches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantha: Day-Night Cycle.
        /// </summary>
        internal static string eventCategory_canthaDayNight {
            get {
                return ResourceManager.GetString("eventCategory-canthaDayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Oasis.
        /// </summary>
        internal static string eventCategory_crystalOasis {
            get {
                return ResourceManager.GetString("eventCategory-crystalOasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day-Night Cycle.
        /// </summary>
        internal static string eventCategory_dayNightCycle {
            get {
                return ResourceManager.GetString("eventCategory-dayNightCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert Highland.
        /// </summary>
        internal static string eventCategory_desertHighland {
            get {
                return ResourceManager.GetString("eventCategory-desertHighland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Desolation.
        /// </summary>
        internal static string eventCategory_desolation {
            get {
                return ResourceManager.GetString("eventCategory-desolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Bash.
        /// </summary>
        internal static string eventCategory_dragonBash {
            get {
                return ResourceManager.GetString("eventCategory-dragonBash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon&apos;s End.
        /// </summary>
        internal static string eventCategory_dragonsEnd {
            get {
                return ResourceManager.GetString("eventCategory-dragonsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Stand.
        /// </summary>
        internal static string eventCategory_dragonStand {
            get {
                return ResourceManager.GetString("eventCategory-dragonStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Top.
        /// </summary>
        internal static string eventCategory_dryTop {
            get {
                return ResourceManager.GetString("eventCategory-dryTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elon Riverlands.
        /// </summary>
        internal static string eventCategory_elonRiverlands {
            get {
                return ResourceManager.GetString("eventCategory-elonRiverlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye of the North.
        /// </summary>
        internal static string eventCategory_eotn {
            get {
                return ResourceManager.GetString("eventCategory-eotn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival of the Four Winds.
        /// </summary>
        internal static string eventCategory_festivalOfTheFourWinds {
            get {
                return ResourceManager.GetString("eventCategory-festivalOfTheFourWinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grothmar Valley.
        /// </summary>
        internal static string eventCategory_grothmar {
            get {
                return ResourceManager.GetString("eventCategory-grothmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween.
        /// </summary>
        internal static string eventCategory_halloween {
            get {
                return ResourceManager.GetString("eventCategory-halloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain of Istan.
        /// </summary>
        internal static string eventCategory_istan {
            get {
                return ResourceManager.GetString("eventCategory-istan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahai Bluffs.
        /// </summary>
        internal static string eventCategory_jahai {
            get {
                return ResourceManager.GetString("eventCategory-jahai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Doric.
        /// </summary>
        internal static string eventCategory_lakeDoric {
            get {
                return ResourceManager.GetString("eventCategory-lakeDoric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley Line Anomaly.
        /// </summary>
        internal static string eventCategory_leyLineAnomaly {
            get {
                return ResourceManager.GetString("eventCategory-leyLineAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Kaineng City.
        /// </summary>
        internal static string eventCategory_newKainengCity {
            get {
                return ResourceManager.GetString("eventCategory-newKainengCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Automated Tournaments.
        /// </summary>
        internal static string eventCategory_pvpTournaments {
            get {
                return ResourceManager.GetString("eventCategory-pvpTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitung Province.
        /// </summary>
        internal static string eventCategory_seitungProvince {
            get {
                return ResourceManager.GetString("eventCategory-seitungProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Reset.
        /// </summary>
        internal static string eventCategory_serverReset {
            get {
                return ResourceManager.GetString("eventCategory-serverReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangled Depth.
        /// </summary>
        internal static string eventCategory_tangledDepth {
            get {
                return ResourceManager.GetString("eventCategory-tangledDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Echovald Wilds.
        /// </summary>
        internal static string eventCategory_theEchovaldWilds {
            get {
                return ResourceManager.GetString("eventCategory-theEchovaldWilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderhead Peaks.
        /// </summary>
        internal static string eventCategory_thunderheadPeaks {
            get {
                return ResourceManager.GetString("eventCategory-thunderheadPeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vabbi.
        /// </summary>
        internal static string eventCategory_vabbi {
            get {
                return ResourceManager.GetString("eventCategory-vabbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdant Brink.
        /// </summary>
        internal static string eventCategory_verdantBrink {
            get {
                return ResourceManager.GetString("eventCategory-verdantBrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Bosses.
        /// </summary>
        internal static string eventCategory_worldBosses {
            get {
                return ResourceManager.GetString("eventCategory-worldBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard World Bosses.
        /// </summary>
        internal static string eventCategory_worldBossesHardcore {
            get {
                return ResourceManager.GetString("eventCategory-worldBossesHardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden states cleared!.
        /// </summary>
        internal static string EventSettingsView_ResetHiddenStates_Success {
            get {
                return ResourceManager.GetString("EventSettingsView_ResetHiddenStates_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset hidden states.
        /// </summary>
        internal static string EventSettingsView_ResetHiddenStates_Title {
            get {
                return ResourceManager.GetString("EventSettingsView_ResetHiddenStates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        internal static string EventSettingsView_UpdateEventFile_Success {
            get {
                return ResourceManager.GetString("EventSettingsView_UpdateEventFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Event File.
        /// </summary>
        internal static string EventSettingsView_UpdateEventFile_Title {
            get {
                return ResourceManager.GetString("EventSettingsView_UpdateEventFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        internal static string ManageEventsView_AllEvents {
            get {
                return ResourceManager.GetString("ManageEventsView_AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string ManageEventsView_CheckAll {
            get {
                return ResourceManager.GetString("ManageEventsView_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Categories.
        /// </summary>
        internal static string ManageEventsView_EventCategories_Title {
            get {
                return ResourceManager.GetString("ManageEventsView_EventCategories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ManageEventsView_SearchBox_Placeholder {
            get {
                return ResourceManager.GetString("ManageEventsView_SearchBox_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all.
        /// </summary>
        internal static string ManageEventsView_UncheckAll {
            get {
                return ResourceManager.GetString("ManageEventsView_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy waypoint.
        /// </summary>
        internal static string ManageEventsView_Waypoint_Description {
            get {
                return ResourceManager.GetString("ManageEventsView_Waypoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string ManageEventsView_Waypoint_Title {
            get {
                return ResourceManager.GetString("ManageEventsView_Waypoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open wiki.
        /// </summary>
        internal static string ManageEventsView_Wiki_Description {
            get {
                return ResourceManager.GetString("ManageEventsView_Wiki_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string ManageEventsView_Wiki_Title {
            get {
                return ResourceManager.GetString("ManageEventsView_Wiki_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should automatically update the exported event file to the newest version..
        /// </summary>
        internal static string Setting_AutomaticallyUpdateEventFile_Description {
            get {
                return ResourceManager.GetString("Setting_AutomaticallyUpdateEventFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Update Event File.
        /// </summary>
        internal static string Setting_AutomaticallyUpdateEventFile_Name {
            get {
                return ResourceManager.GetString("Setting_AutomaticallyUpdateEventFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the background color..
        /// </summary>
        internal static string Setting_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Setting_BackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string Setting_BackgroundColor_Name {
            get {
                return ResourceManager.GetString("Setting_BackgroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the opacity of the background..
        /// </summary>
        internal static string Setting_BackgroundColorOpacity_Description {
            get {
                return ResourceManager.GetString("Setting_BackgroundColorOpacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color Opacity.
        /// </summary>
        internal static string Setting_BackgroundColorOpacity_Name {
            get {
                return ResourceManager.GetString("Setting_BackgroundColorOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should be build from the top or the bottom..
        /// </summary>
        internal static string Setting_BuildDirection_Description {
            get {
                return ResourceManager.GetString("Setting_BuildDirection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Direction.
        /// </summary>
        internal static string Setting_BuildDirection_Name {
            get {
                return ResourceManager.GetString("Setting_BuildDirection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should copy waypoints to clipboard if event has been left clicked..
        /// </summary>
        internal static string Setting_CopyWaypointOnClick_Description {
            get {
                return ResourceManager.GetString("Setting_CopyWaypointOnClick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Waypoints.
        /// </summary>
        internal static string Setting_CopyWaypointOnClick_Name {
            get {
                return ResourceManager.GetString("Setting_CopyWaypointOnClick_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should be running in debug mode..
        /// </summary>
        internal static string Setting_DebugEnabled_Description {
            get {
                return ResourceManager.GetString("Setting_DebugEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Enabled.
        /// </summary>
        internal static string Setting_DebugEnabled_Name {
            get {
                return ResourceManager.GetString("Setting_DebugEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the events should have a small border..
        /// </summary>
        internal static string Setting_DrawEventBorder_Description {
            get {
                return ResourceManager.GetString("Setting_DrawEventBorder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Event Border.
        /// </summary>
        internal static string Setting_DrawEventBorder_Name {
            get {
                return ResourceManager.GetString("Setting_DrawEventBorder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the size of the font used for events..
        /// </summary>
        internal static string Setting_EventFontSize_Description {
            get {
                return ResourceManager.GetString("Setting_EventFontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Font Size.
        /// </summary>
        internal static string Setting_EventFontSize_Name {
            get {
                return ResourceManager.GetString("Setting_EventFontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the height of a single event row..
        /// </summary>
        internal static string Setting_EventHeight_Description {
            get {
                return ResourceManager.GetString("Setting_EventHeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Height.
        /// </summary>
        internal static string Setting_EventHeight_Name {
            get {
                return ResourceManager.GetString("Setting_EventHeight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how much history the timespan should contain..
        /// </summary>
        internal static string Setting_EventHistorySplit_Description {
            get {
                return ResourceManager.GetString("Setting_EventHistorySplit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event History Split.
        /// </summary>
        internal static string Setting_EventHistorySplit_Name {
            get {
                return ResourceManager.GetString("Setting_EventHistorySplit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timespan the event table should cover (in minutes)..
        /// </summary>
        internal static string Setting_EventTimeSpan_Description {
            get {
                return ResourceManager.GetString("Setting_EventTimeSpan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Timespan.
        /// </summary>
        internal static string Setting_EventTimeSpan_Name {
            get {
                return ResourceManager.GetString("Setting_EventTimeSpan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Timespan &apos;{0}&apos; no real number..
        /// </summary>
        internal static string Setting_EventTimeSpan_Validation_NoDouble {
            get {
                return ResourceManager.GetString("Setting_EventTimeSpan_Validation_NoDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Timespan is bigger than {0} minutes. Cap at {0} for performance reasons..
        /// </summary>
        internal static string Setting_EventTimeSpan_Validation_OverLimit {
            get {
                return ResourceManager.GetString("Setting_EventTimeSpan_Validation_OverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the text color of filler events..
        /// </summary>
        internal static string Setting_FillerTextColor_Description {
            get {
                return ResourceManager.GetString("Setting_FillerTextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler Text Color.
        /// </summary>
        internal static string Setting_FillerTextColor_Name {
            get {
                return ResourceManager.GetString("Setting_FillerTextColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should be displayed..
        /// </summary>
        internal static string Setting_GlobalEnabled_Description {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Table Enabled.
        /// </summary>
        internal static string Setting_GlobalEnabled_Name {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keybinding which will toggle the event table..
        /// </summary>
        internal static string Setting_GlobalEnabledHotkey_Description {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabledHotkey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Table Hotkey.
        /// </summary>
        internal static string Setting_GlobalEnabledHotkey_Name {
            get {
                return ResourceManager.GetString("Setting_GlobalEnabledHotkey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should hide when the player is in combat..
        /// </summary>
        internal static string Setting_HideInCombat_Description {
            get {
                return ResourceManager.GetString("Setting_HideInCombat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Combat.
        /// </summary>
        internal static string Setting_HideInCombat_Name {
            get {
                return ResourceManager.GetString("Setting_HideInCombat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should hide when the map is open..
        /// </summary>
        internal static string Setting_HideOnMap_Description {
            get {
                return ResourceManager.GetString("Setting_HideOnMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on open Map.
        /// </summary>
        internal static string Setting_HideOnMap_Name {
            get {
                return ResourceManager.GetString("Setting_HideOnMap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should hide when cutscenes are played..
        /// </summary>
        internal static string Setting_HideOnMissingMumbleTicks_Description {
            get {
                return ResourceManager.GetString("Setting_HideOnMissingMumbleTicks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on Cutscenes.
        /// </summary>
        internal static string Setting_HideOnMissingMumbleTicks_Name {
            get {
                return ResourceManager.GetString("Setting_HideOnMissingMumbleTicks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the event table should be displayed on the X axis..
        /// </summary>
        internal static string Setting_LocationX_Description {
            get {
                return ResourceManager.GetString("Setting_LocationX_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location X.
        /// </summary>
        internal static string Setting_LocationX_Name {
            get {
                return ResourceManager.GetString("Setting_LocationX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the event table should be displayed on the Y axis..
        /// </summary>
        internal static string Setting_LocationY_Description {
            get {
                return ResourceManager.GetString("Setting_LocationY_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Y.
        /// </summary>
        internal static string Setting_LocationY_Name {
            get {
                return ResourceManager.GetString("Setting_LocationY_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the opacity of the event table..
        /// </summary>
        internal static string Setting_Opacity_Description {
            get {
                return ResourceManager.GetString("Setting_Opacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Setting_Opacity_Name {
            get {
                return ResourceManager.GetString("Setting_Opacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should add it&apos;s own corner icon to access settings..
        /// </summary>
        internal static string Setting_RegisterCornerIcon_Description {
            get {
                return ResourceManager.GetString("Setting_RegisterCornerIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Corner Icon.
        /// </summary>
        internal static string Setting_RegisterCornerIcon_Name {
            get {
                return ResourceManager.GetString("Setting_RegisterCornerIcon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should show a context menu if an event has been right clicked..
        /// </summary>
        internal static string Setting_ShowContextMenuOnClick_Description {
            get {
                return ResourceManager.GetString("Setting_ShowContextMenuOnClick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Context Menu.
        /// </summary>
        internal static string Setting_ShowContextMenuOnClick_Name {
            get {
                return ResourceManager.GetString("Setting_ShowContextMenuOnClick_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should display event information on hover..
        /// </summary>
        internal static string Setting_ShowTooltips_Description {
            get {
                return ResourceManager.GetString("Setting_ShowTooltips_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltips.
        /// </summary>
        internal static string Setting_ShowTooltips_Name {
            get {
                return ResourceManager.GetString("Setting_ShowTooltips_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the text color of events..
        /// </summary>
        internal static string Setting_TextColor_Description {
            get {
                return ResourceManager.GetString("Setting_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string Setting_TextColor_Name {
            get {
                return ResourceManager.GetString("Setting_TextColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the mode in which the tooltip times are displayed..
        /// </summary>
        internal static string Setting_TooltipTimeMode_Description {
            get {
                return ResourceManager.GetString("Setting_TooltipTimeMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Time Mode.
        /// </summary>
        internal static string Setting_TooltipTimeMode_Name {
            get {
                return ResourceManager.GetString("Setting_TooltipTimeMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should use the build in translation for events. Needs reload..
        /// </summary>
        internal static string Setting_UseEventTranslation_Description {
            get {
                return ResourceManager.GetString("Setting_UseEventTranslation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Event Translation.
        /// </summary>
        internal static string Setting_UseEventTranslation_Name {
            get {
                return ResourceManager.GetString("Setting_UseEventTranslation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event table should fill empty spaces with filler events..
        /// </summary>
        internal static string Setting_UseFiller_Description {
            get {
                return ResourceManager.GetString("Setting_UseFiller_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Filler Events.
        /// </summary>
        internal static string Setting_UseFiller_Name {
            get {
                return ResourceManager.GetString("Setting_UseFiller_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the event fillers should have names..
        /// </summary>
        internal static string Setting_UseFillerEventNames_Description {
            get {
                return ResourceManager.GetString("Setting_UseFillerEventNames_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Filler Event Names.
        /// </summary>
        internal static string Setting_UseFillerEventNames_Name {
            get {
                return ResourceManager.GetString("Setting_UseFillerEventNames_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the event table..
        /// </summary>
        internal static string Setting_Width_Description {
            get {
                return ResourceManager.GetString("Setting_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Setting_Width_Name {
            get {
                return ResourceManager.GetString("Setting_Width_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the action when a worldboss has been completed..
        /// </summary>
        internal static string Setting_WorldbossCompletedAction_Description {
            get {
                return ResourceManager.GetString("Setting_WorldbossCompletedAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldboss Completed Action.
        /// </summary>
        internal static string Setting_WorldbossCompletedAction_Name {
            get {
                return ResourceManager.GetString("Setting_WorldbossCompletedAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string SettingsView_OpenSettings {
            get {
                return ResourceManager.GetString("SettingsView_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Settings.
        /// </summary>
        internal static string SettingsWindow_EventSettings_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_EventSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string SettingsWindow_GeneralSettings_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_GeneralSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Settings.
        /// </summary>
        internal static string SettingsWindow_GraphicSettings_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_GraphicSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Events.
        /// </summary>
        internal static string SettingsWindow_ManageEvents_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_ManageEvents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindow_Subtitle {
            get {
                return ResourceManager.GetString("SettingsWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Table.
        /// </summary>
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
    }
}
